# Generated by Django 6.0.1 on 2026-02-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Marks/points for this question', max_digits=5),
        ),
    ]
