# Generated by Django 6.0.1 on 2026-02-03 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_marks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='snapshot_data',
            field=models.JSONField(blank=True, help_text='Immutable snapshot when frozen', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='snapshot_version',
            field=models.CharField(blank=True, help_text='Version/checksum of snapshot', max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('frozen', 'Frozen'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Whether this question is optional'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='negative_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Marks deducted for wrong answer', max_digits=5),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='positive_marks',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Marks for correct answer', max_digits=5),
        ),
        migrations.AlterField(
            model_name='exam',
            name='revisable',
            field=models.BooleanField(default=True, help_text='Allow participants to revise answers'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order in exam'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status', 'created_by'], name='api_exam_status_bad354_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['frozen'], name='api_exam_frozen_03013f_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'order'], name='api_examque_exam_id_b5b8de_idx'),
        ),
    ]
